### PR TITLE
refactor: read submission timeout from contract

### PR DESCRIPTION
**Pull request by fnanni-0**
Instead of https://github.com/prodeapp/prodeapp-contracts/pull/3

### CODE REVIEW

**Comment by fnanni-0** [comment]
We could do without the Initialize event altogether actually.

**Comment by rodsouto** [comment]
I think that to be consistent we should choose to add the param to initialize or to read all the params from the contract, either way seems fine to me.

**Comment by fnanni-0** [comment]
I'll remove the `Initialize` event then. I'd rather remove code from the contract.

**Comment by rodsouto** [comment]
We need to remove initialize() and move that logic to handleQuestionsRegistered()

**Comment by fnanni-0** [comment]
> > I'll remove the `Initialize` event then. I'd rather remove code from the contract.
> 
> We should change the subgraph to make all the initialization when the NewTournament Event its emitted, but this event it's from the factory, not in the tournament SC.

working on that

**Comment by fnanni-0** [comment]
Done. Contracts: https://github.com/prodeapp/prodeapp-contracts/commit/ca48b2b2cf3b47ebf715e990baf631cecf139512

**Comment by fnanni-0** [comment]
I removed the owner field which pointed to the factory. Let me know if you need it back.

**Comment by rodsouto** [comment]
We need to deploy the new contracts before merging this PR 👌

**Comment by rodsouto** [comment]
We need to deploy the new contracts before merging this PR 👌

**Comment by rodsouto** [comment]
@fnanni-0 can you add prizeWeights too?

**Pull request merged**
